### ISSUE TITLE
Fitting doesn't work

### ISSUE THREAD

**Issue by georgievgeorgi** [h2020charisma/oranchada#20]
```
Stack Trace:
Traceback (most recent call last):
  File "/home/georgieff/git/oranchada/.venv/lib/python3.10/site-packages/orangecontrib/oranchada/base_widget/base_widget.py", line 47, in force_plot
    self.plot_spe()
  File "/home/georgieff/git/oranchada/.venv/lib/python3.10/site-packages/orangecontrib/oranchada/base_widget/base_widget.py", line 64, in plot_spe
    self.custom_plot(ax)
  File "/home/georgieff/git/oranchada/.venv/lib/python3.10/site-packages/orangecontrib/oranchada/widgets_pro/fit_peaks.py", line 45, in custom_plot
    ListPeakCandidateMultiModel.validate(spe.result).plot(ax)
AttributeError: 'FitPeaksResult' object has no attribute 'result'
```

**Comment by georgievgeorgi** [comment]
Fixed with commit 9398693cffd1bb6e3f646951c54dc21f7974ed20
